<div class="section-newsletter">
	<div class="container">
		<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?> 
	</div>
</div>
<div id="back-top" class="hidden-xs"><i class="fa fa-long-arrow-up"></i></div>
<div class="footer-container">
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-footer')->toHtml(); ?>
				</div>
				<div class="col-md-6 col-xs-12 text-right">
					<?php echo $this->getChildHtml("copyright"); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload = function () {
		document.body.className += " preloaded";
	}
</script>